config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'consent' => 'welcome#consent'

  get 'dashboard' => "dashboard#index"

  get 'experimentation' => "experimentation#index"

  # onboarding
  scope :onboarding, as: :onboarding do
    get '' => 'onboarding#index'
    get 'habits' => 'onboarding#habits'
    post 'habits' => 'onboarding#set_habits'
    get 'reflections' => 'onboarding#reflection_settings'
    post 'reflections' => 'onboarding#set_reflection_settings'
    get 'samplings' => 'onboarding#sampling_settings'
    post 'samplings' => 'onboarding#set_sampling_settings'
    get 'client' => 'onboarding#client'
  end

  # Devise (login/logout) for HTML requests
  devise_for :users, controllers: { registrations: 'registrations' }, defaults: { format: :html }, path: '', sign_out_via: %i[get post delete], path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  devise_scope :user do
    get :settings, to: 'registrations#settings'
    put :settings, to: 'registrations#update_settings'
  end

  # resources will automatically create all CRUD paths
  # the only attribute can be used to limit it to certain actions
  resources :goals

  resources :habits do
    collection do
      get 'select'
      post 'clone'
    end
    member do
      post 'enable'
      post 'disable'
    end
  end

  resources :reflections
  resources :experience_sample_configs

  # API part
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'post/index'
      devise_scope :user do
        post :auth, to: 'sessions#create'
        delete :auth, to: 'sessions#destroy'
      end
      resources :users, only: %w[show] do
        resources :occurrences, only: [:index, :update]
        resources :samplings, only: [:index, :update]
      end
    end
    namespace :v2 do
      # Things yet to come
    end
  end
end

app/controllers/experimentation_controller.rb
class ExperimentationController < ApplicationController
  before_action :authenticate_user!
  layout 'boxed' # sets the layout for all views with this controller

  def index
    param_start = params[:start].to_s
    @start_datetime = param_start.present? ? DateTime.parse(param_start) : DateTime.now.beginning_of_week
    @first_reflection_at = current_user.occurrences.order('scheduled_at').first.scheduled_at

    @goals = current_user.goals

    @current_period_start = @start_datetime.beginning_of_day
    @current_period_end = @current_period_start.end_of_day + 6.days

    @last_period_start = @start_datetime.beginning_of_day - 7.days
    @last_period_end = @current_period_start.end_of_day - 1.days

    @has_data_before_start_date = current_user.created_at < @last_period_end


  end




end

app/helpers/experimentation_helper.rb
module ExperimentationHelper

  def done_occs_from_habit(habit, start_date, end_date)
    habit.occurrences
                .where('scheduled_at >= ?', start_date)
                .where('scheduled_at <= ?', end_date)
                .where('started_at IS NOT NULL').count
                #.where('ended_at IS NOT NULL')

  end

  def total_occs_from_habit(habit, start_date, end_date)
    habit.occurrences
         .where('scheduled_at >= ?', start_date)
         .where('scheduled_at <= ?', end_date)
         .count
  end

  def percentage_change(habit, current_start_date, current_end_date, previous_start_date, previous_end_date)
    current_done = done_occs_from_habit(habit, current_start_date, current_end_date)
    current_total = total_occs_from_habit(habit, current_start_date, current_end_date)
    current_ratio = current_total.zero? ? 0 : current_done.to_f / current_total.to_f

    previous_done = done_occs_from_habit(habit, previous_start_date, previous_end_date)
    previous_total = total_occs_from_habit(habit, previous_start_date, previous_end_date)
    previous_ratio = previous_total.zero? ? 0 : previous_done.to_f / previous_total.to_f


    if previous_ratio.zero?
       current_ratio.zero? ? 0 : 100
    else
      ((current_ratio - previous_ratio) / previous_ratio * 100).round(0)
    end

  end


  def average_self_report(self_reports)
    avg = self_reports.average(:value)
    if avg.nil?
      "-"
    else
      avg.round(2)
    end
  end

  def average_percentage_change(current_avg, previous_avg)
    if current_avg.is_a? Numeric and !previous_avg.is_a? Numeric
      100
    end
    if !current_avg.is_a? Numeric and previous_avg.is_a? Numeric
      -100
    end
    if !current_avg.is_a? Numeric and !previous_avg.is_a? Numeric
      nil
    end
    (((current_avg-previous_avg)/previous_avg) * 100).round(2)
  end

  def subjective_goal_contribution(habit, start_date, end_date)
    avg = habit.habit_reflections
               .where('created_at >= ?', start_date)
               .where('created_at <= ?', end_date)
               .average(:rating)
    if avg.nil?
      nil
    else
      avg.round(2)
    end
  end

end

app/views/experimentation/_add_habits.html.erb
<div class="grid mb-2">
  <div class="flex flex-col mb-4">
    <h3 class="text-lg text-gray-600 font-semibold mb-1">Try a new habit</h3>
    <p class="text-sm text-gray-500">If the existing habits do not positively affect your performance, trying a different habit might help.</p>
  </div>
  <div class="flex flex-row">
    <a class="mr-2 btn btn-secondary inline-block self-start" x-data @click="$dispatch('show-modal', '<%= "new-habit-#{goal.id}" %>')">
      <i class="far fa-plus mr-2"></i>
      Create new Habit
    </a>

    <a class="mr-auto btn btn-secondary inline-block self-start" x-data @click="$dispatch('show-modal', '<%= "add-habits-#{goal.id}" %>')">
      <i class="far fa-wand-magic mr-2"></i>
      Select from Template
    </a>
  </div>


</div>

app/views/experimentation/_add_habits_modal.html.erb
<%= render 'shared/modal', id: "add-habits-#{goal.id}" do %>

  <div class="flex flex-col">
    <div class="flex flex-col border-b border-gray-200 pb-4 mb-4">
      <h2 class="mb-1">Select Habit Template</h2>
      <p class="text-sm text-gray-500">Based on your current experience with yaht, the following list contains new habits you could try towards achieving your goal to <strong><%= goal.title %></strong>.</p>
    </div>
    <% new_habits = new_habits_for_goal(goal) %>
    <% if new_habits.any? %>
      <%= form_with(url: clone_habits_path(:redirect_to => request.path), method: "post") do |form| %>

        <div class="">
          <% new_habits.each_with_index do |habit,index| %>
            <%= render 'habits/habit_select_list', habit: habit %>
          <% end %>
        </div>

        <%= form.submit 'Select Habits', class: 'btn btn-primary mt-2' %>
      <% end %>
    <% else %>
      <%= render "shared/info" do %>
        There are currently no new habits available as a template for this goal.
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/experimentation/_edit_habit_modal.html.erb
<%= render 'shared/modal', id: "edit-habit-#{habit.id}" do %>
  <div class="flex flex-col">
    <div class="flex flex-col border-b border-gray-200 pb-4 mb-4">
      <h2 class="mb-1">Edit Habit</h2>
    </div>
    <%= render 'habits/form', habit: habit, redirect_to: request.path %>
  </div>
<% end %>

app/views/experimentation/_habit.html.erb
<div class="mb-2">
  <div class="flex flex-row <%= !habit.is_enabled ? "opacity-50" : "" %>">
    <h3 class="text-lg text-gray-600 font-semibold mb-1"><%= habit.title %></h3>
    <% unless habit.is_enabled %>
      <div class="ml-2 px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800 self-center justify-self-center">
        Disabled
      </div>
    <% end %>
  </div>

  <div class="text-xs mb-4 <%= !habit.is_enabled ? "opacity-50" : "" %>">
    <span class="text-gray-500">Last change:</span>
    <span class="text-gray-800"><%= time_ago_in_words(habit.updated_at) %> ago</span>
    <span class="ml-4 text-gray-500">Habit added:</span>
    <span class="text-gray-800"><%= time_ago_in_words(habit.created_at) %> ago</span>
  </div>

  <div class="pb-4">
    <div class="grid grid-cols-12 gap-4">
      <div class="col-span-3 rounded border border-gray-100 bg-gray-50 p-4 <%= !habit.is_enabled ? "opacity-50" : "" %>">
        <div class="font-medium text-gray-700 text-xs">
          Completed
        </div>
        <div class="mt-2 text-lg font-semibold text-gray-800">
          <%= done_occs_from_habit(habit, @current_period_start, @current_period_end) %> / <%= total_occs_from_habit(habit, @current_period_start, @current_period_end) %>
          <span class="ml-1 text-xs text-gray-500">
            <%= done_occs_from_habit(habit, @last_period_start, @last_period_end) %>/<%= total_occs_from_habit(habit, @current_period_start, @current_period_end) %>
          </span>
        </div>
        <% if percentage_change(habit, @current_period_start, @current_period_end, @last_period_start, @last_period_end) > 0 %>
          <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
            +<%= percentage_change(habit, @current_period_start, @current_period_end, @last_period_start, @last_period_end) %>%
          </p>
        <% elsif percentage_change(habit, @current_period_start, @current_period_end, @last_period_start, @last_period_end) < 0%>
          <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
            <%= percentage_change(habit, @current_period_start, @current_period_end, @last_period_start, @last_period_end) %>%
          </p>
        <% else %>
          <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-200 text-gray-800">
            no change
          </p>
        <% end %>
      </div>
      <div class="col-span-5 rounded border border-gray-100 bg-gray-50 p-4 <%= !habit.is_enabled ? "opacity-50" : "" %>">
        <div class="flex flex-row">
          <div class="flex-grow font-medium text-gray-700 text-xs">
            Subjective Goal Contribution
          </div>
          <div class="text-gray-400 cursor-pointer hover:text-gray-500 ml-auto -mt-1" data-tippy-content="How much the habit has worked towards achieving your goal (based on your reflections)">
            <i class="fas fa-question-circle"></i>
          </div>
        </div>

        <%
          current_contribution = subjective_goal_contribution(habit, @current_period_start, @current_period_end)
          current_percentage = current_contribution.nil? ? nil : (current_contribution+2)*25
          previous_contribution = subjective_goal_contribution(habit, @last_period_start, @last_period_end)

          if current_contribution.nil? or previous_contribution.nil?
            contribution_change = nil
          else
            contribution_change = current_contribution - previous_contribution
          end

        %>
        <div class="">
          <% if current_contribution.nil? %>
            <p class="text-sm text-gray-500">No data: You have not yet rated this habit in your reflections.</p>
          <% else %>
            <div class="mt-2 text-lg font-semibold text-gray-800">
              <div class="flex flex-row">
                <div class="flex pr-4 w-12"><%= current_contribution %></div>
                <div class="flex flex-row flex-grow relative">
                  <div class="flex-1 bg-red-400 h-3 mt-2 rounded-l-lg" data-tippy-content="Not at all"></div>
                  <div class="flex-1 bg-red-300 h-3 mt-2" data-tippy-content="Not much"></div>
                  <div class="flex-1 bg-green-300 h-3 mt-2 " data-tippy-content="A bit"></div>
                  <div class="flex-1 bg-green-400 h-3 mt-2 rounded-r-lg" data-tippy-content="Definitely"></div>
                  <div class="absolute text-gray-600 text-center h-3" style="transform: translateX(-50%); left: <%= current_percentage %>%">
                    |
                  </div>
                </div>

              </div>
            </div>
            <% if contribution_change %>
              <% if contribution_change > 0 %>
                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800" data-tippy-content="Change compared to previous period">
                  +<%= contribution_change %>
                </p>
              <% elsif contribution_change < 0 %>
                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800" data-tippy-content="Change compared to previous period">
                  <%= contribution_change %>
                </p>
              <% else %>
                <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-200 text-gray-800" data-tippy-content="Change compared to previous period">
                  no change
                </p>
              <% end %>
            <% end %>
        <% end %>
        </div>
      </div>
      <div class="col-span-4 pt-4">
        <div class="space-y-4 float-right">
          <div class="inline-block">
            <a class="btn btn-secondary mr-2" x-data @click="$dispatch('show-modal', '<%= "edit-habit-#{habit.id}" %>')">
              <i class="icon far fa-pencil "></i>Edit
            </a>
          </div>
          <div class="inline-block">
            <% if habit.is_enabled %>
              <%= link_to disable_habit_path(habit, :redirect_to => request.path), method: :post, class: 'btn btn-secondary mr-2'  do %>
                <i class="icon far fa-eye-slash "></i>Disable
              <% end %>
            <% else %>
              <%= link_to enable_habit_path(habit, :redirect_to => request.path), method: :post, class: 'btn btn-secondary mr-2'  do %>
                <i class="icon far fa-eye "></i>Enable
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<%= render "edit_habit_modal", habit: habit %>

app/views/experimentation/_habit_schedule_chart.html.erb
<div class="">
  <%
    chart = {
      datasets: [],
      yLabels: habits.map{ |habit| habit.title }
    }

    chart_id = "habitScheduleChart-#{habits.first.goal.id}"

    habits.each_with_index do |habit,index|
      chart[:datasets].append({
              label: habit.title,
              type: 'scatter',
              backgroundColor: chart_color_value(habits.first.goal.color,0.4 + (index+1)*(0.6/habits.length)),
              data: habit.occurrences.where('scheduled_at >= ?', @current_period_start).where('scheduled_at <= ?', @current_period_end).map { |occ| { x: occ.scheduled_at.iso8601(3), y: habit.title, duration: habit.duration, started: occ.started_at.present?, ended: occ.started_at.present?, skipped: occ.skipped_at.present? } }
      })
    end

  %>
  <div class="text-gray-600 font-semibold">Habit Schedule</div>
  <%= content_tag :canvas, id: chart_id, class: "habitScheduleChart", height: 70,  data: { chart: chart.to_json } do end %>
  <script>
      if(document.querySelectorAll(".habitScheduleChart").length) {

          var chart = document.querySelector("#<%= chart_id %>");
          var data = JSON.parse(chart.dataset.chart);

          const config = {
              data: {
                  datasets: data.datasets,
              },
              options: {
                  responsive: true,
                  legend: {
                      position: 'bottom',
                      align: 'end',
                      display: true,
                      labels: {
                          boxWidth: 20,
                      },
                      onClick: function(e, legendItem) {
                          var index = legendItem.datasetIndex;
                          var ci = this.chart;
                          var meta = ci.getDatasetMeta(index);
                          // See controller.isDatasetVisible comment
                          meta.hidden = meta.hidden === null ? !ci.data.datasets[index].hidden : null;

                          // We hid a dataset ... rerender the chart
                          ci.update();
                      }
                  },
                  tooltips: {
                      intersect: false,
                      mode: 'x',
                      callbacks: {
                          label: function (tooltipItem, data) {
                              var dataset = data.datasets[tooltipItem.datasetIndex]
                              var label = dataset.label || '';
                              var datapoint = dataset.data[tooltipItem.index]

                              if(datapoint.started || datapoint.ended) {
                                  return label
                              } else if(datapoint.skipped) {
                                  return label + " (skipped)";
                              } else {
                                  return label + " (missed)";
                              }

                          }
                      }
                  },
                  plugins: {
                      crosshair: {
                          zoom: {
                              enabled: false
                          },
                          sync: {
                              enabled: true,            // enable trace line syncing with other charts
                              group: 1,                 // chart group
                          },
                      }
                  },
                  layout: {
                      padding: {
                          top: 20,
                          bottom: 20
                      }
                  },
                  elements: {
                      point: {
                          pointStyle: function(ctx) {
                              if(ctx.dataset.data[ctx.dataIndex].started || ctx.dataset.data[ctx.dataIndex].ended) {
                                  return 'rectRounded'
                              }
                              return 'crossRot'
                          },
                          radius: 5,
                          borderColor: function(ctx) {
                              if(ctx.dataset.data[ctx.dataIndex].started || ctx.dataset.data[ctx.dataIndex].ended) {
                                return 'rgba(255,255,255,0)';
                              }
                              return 'rgba(156,163,175,1)';
                          }
                      }
                  },
                  scales: {
                      xAxes: [{
                          bounds: 'ticks',
                          type: 'time',
                          time: {
                              // Luxon format string
                              tooltipFormat: 'DD T',
                              isoWeekday: true,
                              unit: 'day'
                          },
                          title: {
                              display: false,
                              text: 'Date'
                          },
                          ticks: {
                              source: 'auto',
                              min: new Date(<%= @current_period_start.to_i*1000 %>),
                              max: new Date(<%= @current_period_end.beginning_of_day.to_i*1000 %>)
                          }
                      }],
                      yAxes: [{
                          offset: true,
                          title: {
                              display: false,
                          },
                          scaleLabel: {
                              display: false,
                          },
                          type: 'category',
                          labels: data.yLabels,
                          ticks: {
                              display: false,
                              align: ''
                          },
                          gridLines: {
                              offsetGridLines: true,
                              //tickMarkLength: 0
                          }
                      }]
                  }
              }
          };


          var myChart = new Chart(
              chart,
              config
          );
      }
  </script>
</div>

app/views/experimentation/_new_habit_modal.html.erb
<%= render 'shared/modal', id: "new-habit-#{goal.id}" do %>

  <div class="flex flex-col">
    <div class="flex flex-col border-b border-gray-200 pb-4 mb-4">
      <h2 class="mb-1">Create new Habit</h2>
    </div>
    <%= render 'habits/form', habit: HabitForm.new(user: current_user, goal_id: goal.id, is_enabled: true), redirect_to: request.path %>
  </div>

<% end %>

app/views/experimentation/_self_report_chart.html.erb
<!-- Chart Self-Report -->
<%
  empty = (current_self_reports.count == 0 and previous_self_reports.count == 0)
  chart_id = "selfReportSamplingChart-#{self_report.id}"

%>
<div class="-mb-4">

  <% if empty %>
    <p>Empty</p>
  <% else %>
    <%
      chart = {
        current_data: current_self_reports.map { |sampling| { x: sampling.scheduled_at.iso8601(3), y: sampling.value.nil? ? 0 : sampling.value } },
        previous_data: previous_self_reports.map { |sampling| { x: (sampling.scheduled_at + 7.days).iso8601(3), xReal: sampling.scheduled_at.iso8601(3),  y: sampling.value.nil? ? 0 : sampling.value } },
        min: 1,
        max: 1 + self_report.scale_steps-1,
        label: self_report.title
      }
      
    %>
    <%= content_tag :canvas, id: chart_id, class: "self-report-sampling-chart", data: { chart: chart.to_json } do end %>
    <script>

        /**
         * Used to show a small bar on the chart if the value is 0
         * @source https://github.com/chartjs/Chart.js/issues/3915
         * @type Object
         */
        var showZeroPlugin = {
            beforeRender: function (chartInstance) {
                var datasets = chartInstance.config.data.datasets;

                for (var i = 0; i < datasets.length; i++) {
                    var meta = datasets[i]._meta;
                    // It counts up every time you change something on the chart so
                    // this is a way to get the info on whichever index it's at
                    var metaData = meta[Object.keys(meta)[0]];
                    var bars = metaData.data;

                    for (var j = 0; j < bars.length; j++) {
                        var model = bars[j]._model;

                        if (metaData.type === "horizontalBar" && model.base === model.x) {
                            model.x = model.base + 4;
                        } else if (model.base === model.y) {
                            model.y = model.base - 4;
                        }
                    }
                }

            }
        };

        // Enabled by default
        Chart.pluginService.register(showZeroPlugin);


        if(document.querySelectorAll("#<%= chart_id %>").length) {

            var chart = document.querySelector("#<%= chart_id %>");
            var data = JSON.parse(chart.dataset.chart);


            const config = {
                data: {
                    datasets: [{
                        label: "Current week",
                        data: data.current_data,
                        backgroundColor: "<%= chart_color_value(self_report.goal.color,0.4) %>",
                        borderColor: "rgba(96, 165, 250, 1)",
                        hoverBackgroundColor: "<%= chart_color_value(self_report.goal.color, 0.8) %>",
                        barPercentage: 1,
                        categoryPercentage: 1,
                        type: 'bar',
                    },
                        {
                            label: "Previous week",
                            data: data.previous_data,
                            backgroundColor: "rgba(209, 213, 219, 0.8)",
                            borderColor: "rgba(209, 213, 219, 1)",
                            hoverBackgroundColor: "rgba(209, 213, 219, 1)",
                            barPercentage: 1,
                            categoryPercentage: 1,
                            type: 'bar',
                        }]
                },
                options: {
                    responsive: true,
                    legend: {
                        position: 'bottom',
                        align: 'end',
                        display: true,
                        labels: {
                            boxWidth: 20,
                        },
                    },
                    tooltips: {
                        intersect: false,
                        mode: 'x'
                    },
                    plugins: {
                        crosshair: {
                            zoom: {
                                enabled: false
                            },
                            sync: {
                                enabled: true,            // enable trace line syncing with other charts
                                group: 1,                 // chart group
                            },
                        }
                    },
                    layout: {
                        padding: {
                            top: 20,
                            bottom: 0
                        }
                    },
                    scales: {
                        xAxes: [{
                            bounds: 'ticks',
                            type: 'time',
                            stacked: true,
                            time: {
                                // Luxon format string
                                tooltipFormat: 'DD T',
                                isoWeekday: true,
                                unit: 'day'
                            },
                            title: {
                                display: false,
                                text: 'Date'
                            },
                            ticks: {
                                source: 'auto',
                                min: new Date(<%= @current_period_start.to_i*1000 %>),
                                max: new Date(<%= @current_period_end.beginning_of_day.to_i*1000 %>)
                            }
                        }],
                        yAxes: [{
                            beginAtZero: true,
                            stacked: false,
                            title: {
                                display: false,
                            },
                            ticks: {
                                callback: function(value, index, values) {
                                    if(value % 1 === 0) {
                                        return value;
                                    }
                                },
                                min: 0,
                                max: data.max + 0.5, // prevents top clipping
                            }
                        }]
                    }
                }
            };


            var myChart = new Chart(
                chart,
                config
            );
        }
    </script>
  <% end %>

</div>

app/views/experimentation/_self_report_chart_header.html.erb
<div class="">
  <div class="flex flex-row">
    <div class="flex flex-col">
      <div class="text-gray-600 font-semibold">Self Report: <%= self_report.title %></div>
      <div class="text-sm text-gray-400"><%= self_report.prompt %></div>
    </div>
    <div class="flex flex-row ml-auto pb-2">
      <div class="flex flex-col">
        <div class="<%= color_text_class(self_report.goal.color) %> font-semibold text-sm">Avg. <%= self_report.title %></div>
        <div class="text-gray-400 text-sm">Current</div>
      </div>
      <div class="flex justify-center items-center ml-4">
        <div class="<%= color_text_class(self_report.goal.color) %> font-semibold text-lg">
          <%= average_self_report(current_self_reports) %>
        </div>
      </div>
    </div>
    <div class="flex flex-row ml-4 pb-2">
      <div class="flex flex-col border-l border-gray-200 pl-4">
        <div class="text-gray-400 font-semibold text-sm">Avg. <%= self_report.title %></div>
        <div class="text-gray-400 text-sm">Previous</div>
      </div>
      <div class="flex justify-center items-center ml-4">
        <div class="text-gray-400 font-semibold text-lg">
          <%= average_self_report(previous_self_reports) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experimentation/index.html.erb
<%= render 'shared/page_heading', title: "Self-Experimentation", description: "Is it time for a change? Based on your past reflections and self-reports you can experiment with the settings of your existing habits, add and remove habits." do %>
<% end %>

<div class="flex flex-row pb-4 mb-4">
  <div class="grid grid-cols-3 gap-4">
    <div class="rounded border border-gray-100 bg-gray-50 p-4">
      <div class="font-medium text-gray-700 text-xs">
        Current Period
      </div>
      <div class="mt-2 text-lg font-semibold text-gray-800">
        Last 7 days
      </div>

      <div class="mt-2 font-medium text-gray-600 text-xs">
        <%= @current_period_start.to_date.strftime("%d.%m.%y") %> <%= " - " + @current_period_end.strftime("%d.%m.%y") %>
      </div>
    </div>
    <% if @has_data_before_start_date %>

      <div class="rounded border border-gray-100 bg-gray-50 p-4">
        <div class="font-medium text-gray-700 text-xs">
          Previous Period
        </div>
        <div class="mt-2 text-lg font-semibold text-gray-800">
          Previous 7 days
        </div>

        <div class="mt-2 font-medium text-gray-600 text-xs">
          <%= @last_period_start.to_date.strftime("%d.%m.%y") %> <%= " - " + @last_period_end.to_date.strftime("%d.%m.%y") %>
        </div>
      </div>

    <% end %>
  </div>
</div>


<div class="flow-root">
  <% @goals.each do |goal| %>
    <div class="flex flex-row mb-12 border-b border-gray-200 pb-8">
      <div class="flex-grow">
        <h2 class="text-2xl font-serif mb-2"><i class="far fa-bullseye-arrow text-xl mx-auto"></i> <%= goal.title %></h2>


        <% goal.experience_sample_configs.each do |self_report| %>

          <%
            current_self_reports = self_report.samplings.where('scheduled_at >= ?', @current_period_start).where('scheduled_at <= ?', @current_period_end)
            previous_self_reports = self_report.samplings.where('scheduled_at >= ?', @last_period_start).where('scheduled_at <= ?', @last_period_end)
          %>

          <%= render "self_report_chart_header", self_report: self_report, current_self_reports: current_self_reports, previous_self_reports: previous_self_reports %>
          <%= render "self_report_chart", self_report: self_report, current_self_reports: current_self_reports, previous_self_reports: previous_self_reports %>
        <% end %>
        <% if goal.habits.any? %>
          <%= render "habit_schedule_chart", habits: goal.habits %>
        <% end %>
        <%= render partial: "habit", collection: goal.habits %>
        <%= render "add_habits", goal: goal %>
      </div>
    </div>
    <%= render "add_habits_modal", goal: goal %>
    <%= render "new_habit_modal", goal: goal %>
  <% end %>
</div>