config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'consent' => 'welcome#consent'

  get 'dashboard' => "dashboard#index"

  get 'experimentation' => "experimentation#index"

  # onboarding
  scope :onboarding, as: :onboarding do
    get '' => 'onboarding#index'
    get 'habits' => 'onboarding#habits'
    post 'habits' => 'onboarding#set_habits'
    get 'reflections' => 'onboarding#reflection_settings'
    post 'reflections' => 'onboarding#set_reflection_settings'
    get 'samplings' => 'onboarding#sampling_settings'
    post 'samplings' => 'onboarding#set_sampling_settings'
    get 'client' => 'onboarding#client'
  end

  # Devise (login/logout) for HTML requests
  devise_for :users, controllers: { registrations: 'registrations' }, defaults: { format: :html }, path: '', sign_out_via: %i[get post delete], path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  devise_scope :user do
    get :settings, to: 'registrations#settings'
    put :settings, to: 'registrations#update_settings'
  end

  # resources will automatically create all CRUD paths
  # the only attribute can be used to limit it to certain actions
  resources :goals

  resources :habits do
    collection do
      get 'select'
      post 'clone'
    end
    member do
      post 'enable'
      post 'disable'
    end
  end

  resources :reflections
  resources :experience_sample_configs

  # API part
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'post/index'
      devise_scope :user do
        post :auth, to: 'sessions#create'
        delete :auth, to: 'sessions#destroy'
      end
      resources :users, only: %w[show] do
        resources :occurrences, only: [:index, :update]
        resources :samplings, only: [:index, :update]
      end
    end
    namespace :v2 do
      # Things yet to come
    end
  end
end

app/models/experience_sample_config.rb
class ExperienceSampleConfig < ApplicationRecord
  acts_as_paranoid # soft delete

  belongs_to :user
  belongs_to :goal, with_deleted: true
  has_many :samplings

  include Schedulable
  include_schedule :schedule

  validates :title, presence: true
  after_save :schedule_samplings # TODO: later this action must be performed when a habit is *duplicated* and on a daily schedule

  before_destroy :before_destroy
  after_recover :reschedule_samplings # after soft delete recovery

  def before_destroy
    destroy_samplings
  end

  def destroy_samplings
    if deleted?
      samplings.delete_all
    else
      samplings.where("scheduled_at >= ?", DateTime.now).delete_all
    end
  end

  def reschedule_samplings
    schedule_samplings(DateTime.now)
  end

  def schedule_samplings(starting_from = self.updated_at, retention_period = 7.days)

    Sampling.transaction do
      # 1. remove all samplings newer than current updated_at
      samplings.where("scheduled_at >= ?", starting_from).delete_all

      # 2. create new samplings newer than current updated_at
      dates = self.get_schedule(starting: starting_from, ending: (starting_from + retention_period).at_end_of_day)
      dates.each do |date|
        Sampling.create!(experience_sample_config_id: self.id, scheduled_at: date)
      end
    end
  end

end

app/controllers/experience_sample_configs_controller.rb
class ExperienceSampleConfigsController < ApplicationController
  before_action :set_experience_sample_config, only: %i[ show edit update destroy ]

  layout 'boxed' # sets the layout for all views with this controller

  # GET /experience_sample_configs
  def index
    show = params[:show].to_s

    case show
    when "own"
      @experience_sample_configs = current_user.experience_sample_configs
    when "trash"
      @experience_sample_configs = policy_scope(ExperienceSampleConfig).only_deleted
    else
      @experience_sample_configs = policy_scope(ExperienceSampleConfig)
    end

  end

  # GET /experience_sample_configs/1
  def show
    authorize @experience_sample_config
    @current_samplings = @experience_sample_config.samplings.where('scheduled_at <= ?', DateTime.now).order(scheduled_at: :asc)
    @chart = {
      data: @current_samplings.map { |sampling| { x: sampling.scheduled_at.iso8601(3), y: sampling.value} },
      min: 1,
      max: 1 + @experience_sample_config.scale_steps-1,
      label: @experience_sample_config.title
    }
    fortnight_ago = DateTime.now.beginning_of_week - 7.days
    @samplings = @experience_sample_config.samplings.where('scheduled_at > ?', fortnight_ago ).order(scheduled_at: :asc).limit(336)
  end

  # GET /experience_sample_configs/new
  def new
    @experience_sample_config = ExperienceSampleConfig.new(user: current_user)
  end

  # GET /experience_sample_configs/1/edit
  def edit
    authorize @experience_sample_config
  end

  # POST /experience_sample_configs
  def create
    @experience_sample_config = ExperienceSampleConfig.new(experience_sample_config_params)

    respond_to do |format|
      if @experience_sample_config.save
        format.html { redirect_to @experience_sample_config, notice: "Self-Report config was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experience_sample_configs/1
  def update
    authorize @experience_sample_config
    respond_to do |format|
      if @experience_sample_config.update(experience_sample_config_params)
        format.html { redirect_to @experience_sample_config, notice: "Self-Report config was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experience_sample_configs/1
  def destroy
    authorize @experience_sample_config
    @experience_sample_config.destroy
    respond_to do |format|
      format.html { redirect_to experience_sample_configs_url, notice: "Self-Report config was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience_sample_config
      @experience_sample_config = ExperienceSampleConfig.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_sample_config_params
      params.require(:experience_sample_config).permit(:title, :prompt, :scale_steps, :scale_label_start, :scale_label_center, :scale_label_end, :user_id, :goal_id ,:recurrence_at, :recurrence_on => [])
    end
end

app/helpers/experience_sample_configs_helper.rb
module ExperienceSampleConfigsHelper
end

app/views/experience_sample_configs/_form.html.erb
<%= form_with(model: experience_sample_config) do |form| %>
  <% if experience_sample_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience_sample_config.errors.count, "error") %> prohibited this experience_sample_config from being saved:</h2>

      <ul>
        <% experience_sample_config.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title %>
        </div>
      </div>
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :prompt %>
          <%= form.text_field :prompt %>
          <p class="mt-2 text-sm text-gray-500">The question that will be displayed in the prompt.</p>
        </div>
      </div>
    </div>

  <div class="" x-data="{ showAdvancedOptions: false }">
    <div class="text-right text-sm text-gray-500 hover:text-gray-700">
      <span class="cursor-pointer underline" @click="showAdvancedOptions=!showAdvancedOptions">
        <span x-show="showAdvancedOptions">Hide</span><span x-show="!showAdvancedOptions">Show</span> advanced options
      </span>
    </div>
    <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6 overflow-hidden transition-all max-h-0 duration-200"
      style=""
      x-ref="advancedOptionsContainer"
      x-bind:style="showAdvancedOptions == true ? 'max-height: ' + $refs.advancedOptionsContainer.scrollHeight + 'px' : ''"
    >
      <div class="sm:col-span-6 border-gray-100 border-b pb-4 -mb-2 mt-4">
        <h3 class="text-lg mb-2">Scale Configuration:</h3>
        <p class="text-gray-500">Define the scale's steps and its labels that will be shown in the self-report.</p>
      </div>
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :scale_steps %>
          <%= form.number_field :scale_steps, min: 3, max: 10 %>
          <p class="mt-2 text-sm text-gray-500">The number of steps in your scale.</p>
        </div>
      </div>
      <div class="sm:col-span-2">
        <div class="field">
          <%= form.label :scale_label_start %>
          <%= form.text_field :scale_label_start, maxlength: 25 %>
        </div>
      </div>
      <div class="sm:col-span-2">
        <div class="field">
          <%= form.label :scale_label_center %>
          <%= form.text_field :scale_label_center, maxlength: 25 %>
        </div>
      </div>
      <div class="sm:col-span-2">
        <div class="field">
          <%= form.label :scale_label_end %>
          <%= form.text_field :scale_label_end, maxlength: 25 %>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-5 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-6 border-gray-100 border-b pb-4 -mb-2 mt-4">
      <h3 class="text-lg mb-2">Schedule:</h3>
      <p class="text-gray-500">Define the schedule for the notifications that ask you for the self-report.</p>
    </div>
    <div class="sm:col-span-3">
      <div class="field">
        <%= form.label :recurrence_on, "On" %>
        <div class="grid grid-flow-col grid-cols-3 grid-rows-3 gap-2">
          <% [ {label: "Mon", value: "monday"}, {label: "Tue", value: "tuesday"}, {label: "Wed", value: "wednesday"}, {label: "Thu", value: "thursday"}, {label: "Fri", value: "friday"}, {label: "Sat", value: "saturday"}, {label: "Sun", value: "sunday"}].each_with_index do |day,i| %>
            <div class="relative flex items-start">
              <div class="flex items-center h-5">
                <%= form.check_box :recurrence_on, { multiple: true, id: "day_#{i}" }, day[:value], false %>
              </div>
              <div class="ml-3 text-sm">
                <%= form.label day[:label], for: "day_#{i}" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="sm:col-span-3">
      <div class="field">
        <%= form.label :recurrence_at, "At" %>
        <%= form.text_field :recurrence_at,  {class: 'js-choice', multiple: false} %>
        <p class="mt-2 text-sm text-gray-500">Format: HH:MM. Separate multiple values with a comma.</p>
      </div>
    </div>

    <% if policy(experience_sample_config).set_goal? %>
    <div class="sm:col-span-6">
      <div class="field">
        <%= form.label :goal_id %>
        <% if experience_sample_config.user.present?
             goals = experience_sample_config.user.goals
           else
             goals = policy_scope(Goal)
           end
        %>
        <%= form.select :goal_id, goals.collect { |g| [ g.title, g.id] }, include_blank: true %>
      </div>
    </div>
    <% else %>
      <%= form.hidden_field :goal_id %>
    <% end %>

    <% if policy(experience_sample_config).set_user? %>
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :user_id %>
          <%= form.select :user_id, User.all.collect { |u| [ u.username, u.id] } %>
        </div>
      </div>
    <% else %>
      <%= form.hidden_field :user_id %>
    <% end %>
  </div>
  <div class="flex my-4">
    <%= form.submit class: 'btn btn-primary' %>
    <% if experience_sample_config.persisted? %>
      <%= link_to experience_sample_config, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary ml-auto'  do %>
        <i class="icon far fa-trash-alt "></i>Delete Config
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/experience_sample_configs/_preview.html.erb
<div class="bg-gray-200 px-4 py-8 rounded-lg">
  <div class="mx-auto max-w-md w-full bg-white shadow-lg rounded-lg pointer-events-auto flex flex-col ring-1 ring-black ring-opacity-5">
    <div class="flex justify-between items-center w-full pointer-events-auto px-2 py-1 bg-gray-100 text-gray-500 text-xs rounded-t-lg">
      <div class="inline-flex items-center">
        <%= image_tag "yaht-icon.png", class: "inline w-5 h-5 mr-1", alt: "yaht - yet another habit tracker" %>
        Self-Report: <%= sampling.title %>
      </div>
      <div><%= Time.now.strftime("%H:%M") %></div>
    </div>
    <div class="w-full pointer-events-auto flex flex-row">
      <div class="w-0 flex-1 p-4 pt-1">
        <div class="flex items-start">
          <div class="w-0 flex-1">
            <p class="font-medium text-gray-900">
              <%= sampling.prompt %>
            </p>
            <div class="flex flex-row justify-between mt-2 -mx-2">
              <% sampling.scale_steps.times do |index| %>
                <div class="mx-1 flex w-8 h-8 bg-gray-100 text-center items-center text-gray-500 align-middle rounded-md border border-gray-200 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-gray-900 cursor-pointer transition-all">
                  <span class="flex mx-auto font-medium">
                    <%= index %>
                  </span>
                </div>
              <% end %>
            </div>
            <div class="flex flex-row text-gray-400 text-sm mt-1">
              <div class="">
                <%= sampling.scale_label_start %>
              </div>
              <div class="mx-auto">
                <%= sampling.scale_label_center %>
              </div>
              <div class="">
                <%= sampling.scale_label_end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        class="flex border-l border-gray-200 cursor-pointer"
      >
        <div
          class="w-full border border-transparent rounded-none rounded-r-lg p-4 flex items-center justify-center text-sm font-medium text-gray-600 hover:text-gray-900 focus:outline-none"
        >
          Skip
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experience_sample_configs/_self_report_config_list.html.erb
<li>
  <a href="<%= experience_sample_config_url(sampling) %>" class="flex flex-row hover:bg-gray-50">
    <div class="flex-none w-1 mr-1 <%= color_bg_class(sampling.goal.color) %>"></div>
    <div class="flex flex-grow flex-col px-4 py-4">
      <div class="flex items-center justify-between">
        <div class="flex flex-col">
          <p class="text-sm font-medium text-gray-900 truncate">
            <%= sampling.title %>
          </p>
          <p class="text-sm text-gray-500 truncate">
            <%= sampling.prompt %>
          </p>
        </div>
      </div>
      <div class="mt-2 sm:flex sm:justify-between">
        <div class="sm:flex">
          <p class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
            <i class="far fa-user mr-2"></i>
            <%= sampling.user.username %>
          </p>
        </div>
        <div class="sm:flex">
          <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
            <i class="far fa-calendar-alt mr-2"></i>
            <p>
              <%= sampling.recurrence_on.map{|day| day.slice(0,2)}.join(', ') %> at <%= sampling.recurrence_at %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </a>
</li>

app/views/experience_sample_configs/edit.html.erb
<h1>Editing Self-Report Config</h1>

<%= render 'form', experience_sample_config: @experience_sample_config %>

<%= link_to 'Show', @experience_sample_config %> |
<%= link_to 'Back', experience_sample_configs_path %>

app/views/experience_sample_configs/index.html.erb
<%= render 'shared/page_heading', title: "Self-Reports", description: "Self-Reports help you to continuously monitor and self-report important metrics to track your progress over time." do %>
  <%= link_to 'New Self-Report', new_experience_sample_config_path, class: "btn btn-primary flex whitespace-nowrap" %>
<% end %>

<% if policy(ExperienceSampleConfig).see_all? %>
  <div class="flex flex-row mb-4 items-center justify-end">
    <%= render 'shared/buttongroup', options: [{ title: "All", link: experience_sample_configs_path}, { title: "Own", link: experience_sample_configs_path(:show => :own)}, { title: "Trash", link: experience_sample_configs_path(:show => :trash)}] %>
  </div>
<% end %>


<%= render 'shared/boxed_list' do %>
  <% @experience_sample_configs.each_with_index do |sampling,index| %>
    <%= render 'self_report_config_list', sampling: sampling, index: index %>
  <% end %>
<% end %>

app/views/experience_sample_configs/new.html.erb
<h1>New Self-Report Config</h1>

<%= render 'form', experience_sample_config: @experience_sample_config %>

<%= link_to 'Back', experience_sample_configs_path %>

app/views/experience_sample_configs/show.html.erb
<%= render 'shared/page_heading', title: "Self-Report: #{@experience_sample_config.title}", description: "" do %>
  <%= link_to 'Edit', edit_experience_sample_config_path(@experience_sample_config), class: "btn btn-primary flex whitespace-nowrap" %>
<% end %>

<div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
  <i class="far fa-calendar-alt mr-2"></i>
  <p>
    <%= @experience_sample_config.recurrence_on.map{|day| day.slice(0,2)}.join(', ') %> at <%= @experience_sample_config.recurrence_at %>
  </p>
</div>

<div class="sm:flex">
  <p class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
    <i class="far fa-user mr-2"></i>
    <%= @experience_sample_config.user.username %>
  </p>
</div>

<div class="my-4">
  <h3>Preview:</h3>
  <%= render 'preview', sampling: @experience_sample_config %>
</div>
<h3>Chart:</h3>
<% data = { foo: :bar} %>
<%= content_tag :canvas, id: "myChart", class: "sampling-chart", data: { chart: @chart.to_json } do %><% end %>



<h3>Self-Reports:</h3>

<%= render 'shared/table/wrapper' do %>
  <thead class="bg-gray-50">
    <tr>
      <%= render 'shared/table/heading', title: "ID" %>
      <%= render 'shared/table/heading', title: "Scheduled at" %>
      <%= render 'shared/table/heading', title: "Sampled at" %>
      <%= render 'shared/table/heading', title: "Skipped at" %>
      <%= render 'shared/table/heading', title: "Value" %>
    </tr>
  </thead>
  <tbody>
    <% @samplings.each_with_index do |sampling,index| %>
      <!-- Odd row -->
      <%= render 'shared/table/row', odd: index.even? do %>
        <%= render 'shared/table/cell' do %>
          <%= sampling.id %>
        <% end %>
        <%= render 'shared/table/cell' do %>
          <%= sampling.scheduled_at.strftime("%F %H:%M") %>
        <% end %>
        <%= render 'shared/table/cell' do %>
          <%= sampling.sampled_at&.strftime("%F %H:%M") %>
        <% end %>
        <%= render 'shared/table/cell' do %>
          <%= sampling.skipped_at&.strftime("%F %H:%M") %>
        <% end %>
        <%= render 'shared/table/cell', css_class: 'font-medium' do %>
          <%= sampling.value %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
<% end %>