config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'consent' => 'welcome#consent'

  get 'dashboard' => "dashboard#index"

  get 'experimentation' => "experimentation#index"

  # onboarding
  scope :onboarding, as: :onboarding do
    get '' => 'onboarding#index'
    get 'habits' => 'onboarding#habits'
    post 'habits' => 'onboarding#set_habits'
    get 'reflections' => 'onboarding#reflection_settings'
    post 'reflections' => 'onboarding#set_reflection_settings'
    get 'samplings' => 'onboarding#sampling_settings'
    post 'samplings' => 'onboarding#set_sampling_settings'
    get 'client' => 'onboarding#client'
  end

  # Devise (login/logout) for HTML requests
  devise_for :users, controllers: { registrations: 'registrations' }, defaults: { format: :html }, path: '', sign_out_via: %i[get post delete], path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  devise_scope :user do
    get :settings, to: 'registrations#settings'
    put :settings, to: 'registrations#update_settings'
  end

  # resources will automatically create all CRUD paths
  # the only attribute can be used to limit it to certain actions
  resources :goals

  resources :habits do
    collection do
      get 'select'
      post 'clone'
    end
    member do
      post 'enable'
      post 'disable'
    end
  end

  resources :reflections
  resources :experience_sample_configs

  # API part
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'post/index'
      devise_scope :user do
        post :auth, to: 'sessions#create'
        delete :auth, to: 'sessions#destroy'
      end
      resources :users, only: %w[show] do
        resources :occurrences, only: [:index, :update]
        resources :samplings, only: [:index, :update]
      end
    end
    namespace :v2 do
      # Things yet to come
    end
  end
end

app/views/shared/_boxed_list.html.erb
<div class="bg-white overflow-hidden sm:rounded-md border border-gray-200">
  <ul class="divide-y divide-gray-200">
    <%= yield %>
  </ul>
</div>

app/views/shared/_buttongroup.html.erb
<%
  # options: list of options
  #   link : the page / object to be linked to
%>
<span class="relative z-0 inline-flex shadow-sm rounded-md">
  <% options.each_with_index do |option,index| %>
      <%
        path = request.env['ORIGINAL_FULLPATH']
        first = index == 0
        last = index == options.length-1
        active = path == option[:link]
      %>
      <%= link_to option[:link], class: "#{!first ? "-ml-px" : ""} #{first ? "rounded-l-md" : ""} #{last ? "rounded-r-md" : ""} relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm #{active ? "font-bold text-gray-900" : "font-medium text-gray-700"} hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-gray-900 focus:border-gray-900" do %>
        <%= option[:title] %>
      <% end %>
  <% end %>
</span>

app/views/shared/_footer.html.erb
<footer class="w-full">
  <div class="py-6 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center space-x-6 md:order-3 text-base text-gray-400">
      <div class="mr-4">
        <a href="mailto:help@yaht.app" class="text-gray-600 hover:text-gray-800">
          <i class="fas fa-question-circle mr-0.5"></i>
          Help
        </a>
      </div>
      <%= ENV['HEROKU_RELEASE_VERSION'] ? ENV['HEROKU_RELEASE_VERSION'] : "v-dev" %>
    </div>
    <div class="mt-8 md:mt-0 md:order-1">
      <p class="text-center text-base text-gray-400">
        &copy; <%= Time.new.year %> yaht.app All rights reserved.
      </p>
    </div>
  </div>
</footer>

app/views/shared/_info.html.erb
<div class="rounded-md bg-gray-100 border border-gray-200 my-4 p-4">
  <div class="flex">
    <div class="flex-shrink-0">
      <i class="far fa-info-circle h-5 w-5 text-gray-400"></i>
    </div>
    <div class="ml-3 flex-1 md:flex md:justify-between">
      <div class="m-0 text-gray-700">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_main_menu.html.erb
<div class="max-w-3xl w-full mx-auto sm:px-6 lg:px-8 grid grid-rows-1 grid-cols-3 items-center">
  <a href="<%= dashboard_url %>" class="justify-self-start">
    <%= image_tag "yaht-logomark.svg", class: "mx-auto w-auto h-6", alt: "yaht - yet another habit tracker" %>
  </a>
  <div class="flex flex-col relative justify-self-center self-center" x-data="{ open: false }" @click.away="open=false">
    <!-- Main Menue Button -->
    <div class="flex flex-row mx-auto my-3 items-center cursor-pointer text-gray-700 hover:text-gray-900 transition-all" @click="open=!open">
      <div class="font-medium mr-1">Menu</div>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
      </svg>
    </div>
    <!-- Menue -->
    <div class="absolute origin-top top-full transform left-1/2 -translate-x-1/2 bg-white p-2 w-100 rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none z-10 "
         x-show="open"
         x-transition:enter="transition ease-out duration-100"
         x-transition:enter-start="transform opacity-0 scale-95"
         x-transition:enter-end="transform opacity-100 scale-100"
         x-transition:leave="transition ease-in duration-75"
         x-transition:leave-start="transform opacity-100 scale-100"
         x-transition:leave-end="transform opacity-0 scale-95"
    >
      <div class="grid grid-cols-3 gap-3">
        <a href="<%= dashboard_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-home-lg-alt text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Home</div>
        </a>
        <a href="<%= goals_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-bullseye-arrow text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Goals</div>
        </a>
        <a href="<%= habits_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-stars text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Habits</div>
        </a>
        <a href="<%= reflections_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-pen-nib text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Reflections</div>
        </a>
        <a href="<%= experience_sample_configs_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-ruler-triangle text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Self-Reports</div>
        </a>
        <a href="<%= experimentation_url %>" class="flex flex-col transition rounded-lg bg-white text-gray-600 hover:bg-gray-100 hover:text-gray-700 cursor-pointer p-5">
          <div class="flex">
            <i class="far fa-analytics text-2xl mx-auto"></i>
          </div>
          <div class="text-center font-medium mt-2">Experiment</div>
        </a>
      </div>
    </div>
  </div>
  <div class="relative inline-block text-left justify-self-end" x-data="{ open: false }" @click.away="open=false">
    <div>
      <button type="button" class="h-8 w-8 bg-gray-400 items-center justify-center flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900" id="user-menu-button" aria-expanded="false" aria-haspopup="true" @click="open=!open">
        <span class="text-sm font-medium leading-none text-white"><%= current_user.username[0,1].upcase %></span>
      </button>
    </div>
    <div class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none z-10" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1"
         x-show="open"
         x-transition:enter="transition ease-out duration-100"
         x-transition:enter-start="transform opacity-0 scale-95"
         x-transition:enter-end="transform opacity-100 scale-100"
         x-transition:leave="transition ease-in duration-75"
         x-transition:leave-start="transform opacity-100 scale-100"
         x-transition:leave-end="transform opacity-0 scale-95"
    >
      <div class="px-4 py-3" role="none">
        <p class="text-sm" role="none">
          Signed in as
        </p>
        <p class="text-sm font-medium text-gray-900 truncate" role="none">
          <%= current_user.username %>
        </p>
      </div>
      <div class="py-1" role="none">
        <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
        <%= link_to "Settings", settings_path(current_user), class: "text-gray-700 block px-4 py-2 text-sm hover:text-gray-900" %>
      </div>
      <div class="py-1" role="none">
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true }, class: "text-gray-700 block w-full text-left px-4 py-2 text-sm hover:text-gray-900" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div
  id="<%= id %>"
  class="fixed z-10 inset-0 overflow-y-auto"
  x-data="window.Modal()"
  x-spread="container"
  x-cloak
>
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.
    -->
    <div class="fixed inset-0 transition-opacity" x-spread="overlay">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>&#8203;
    <!--
      Modal panel, show/hide based on modal state.
    -->
    <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-2xl sm:w-full sm:p-6"
         role="dialog"
         aria-modal="true"
         aria-labelledby="modal-headline"
         x-spread="modal"
    >
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="">
  <div class="relative pt-6 pb-6" x-data="{ open: false }">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <nav class="relative flex items-center justify-between sm:h-10 md:justify-center" aria-label="Global">
        <div class="flex items-center flex-1 md:absolute md:inset-y-0 md:left-0">
          <div class="flex items-center justify-between w-full md:w-auto">
            <a href="<%= root_url %>">
              <%= image_tag "yaht-logo.svg", class: "mx-auto w-auto h-8", alt: "yaht - yet another habit tracker" %>
            </a>
            <div class="-mr-2 flex items-center md:hidden">
              <button type="button" @click="open=true" class="bg-gray-50 rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-gray-900" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <!-- Heroicon name: outline/menu -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div class="hidden md:flex md:space-x-10">
          <!--
          <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Product</a>

          <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Features</a>

          <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Marketplace</a>

          <a href="#" class="font-medium text-gray-500 hover:text-gray-900">Company</a>
          -->
        </div>
        <div class="hidden md:absolute md:flex md:items-center md:justify-end md:inset-y-0 md:right-0">
          <% if current_user.present? %>
            <%= link_to dashboard_path, class: 'btn btn-secondary'  do %>
              <i class="icon far fa-sign-in "></i>Open App
            <% end %>
          <% else %>
              <%= link_to "Log in", new_user_session_url,  class: "btn btn-secondary inline-flex mr-2" %>
              <%= link_to "Sign up for free", new_user_registration_url,  class: "btn btn-primary inline-flex" %>
          <% end %>
        </div>
      </nav>
    </div>

    <!--
      Mobile menu, show/hide based on menu open state.

      Entering: "duration-150 ease-out"
        From: "opacity-0 scale-95"
        To: "opacity-100 scale-100"
      Leaving: "duration-100 ease-in"
        From: "opacity-100 scale-100"
        To: "opacity-0 scale-95"
    -->
    <div class="absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden z-10"
         x-show="open"
         x-transition:enter= "duration-150 ease-out"
         x-transition:enter-start="opacity-0 scale-95"
         x-transition:enter-end="opacity-100 scale-100"
         x-transition:leave="duration-100 ease-in"
         x-transition:leave-start="opacity-100 scale-100"
         x-transition:leave-end="opacity-0 scale-95"
    >
      <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
        <div class="px-5 pt-4 flex items-center justify-between">
          <div>
            <a href="<%= root_url %>">
              <%= image_tag "yaht-logomark.svg", class: "w-auto h-6", alt: "yaht - yet another habit tracker" %>
            </a>
          </div>
          <div class="-mr-2">
            <button type="button" @click="open=false" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-gray-900">
              <span class="sr-only">Close main menu</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="px-2 pt-2 pb-3 space-y-1">
          <!--
          <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Product</a>

          <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Features</a>

          <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Marketplace</a>

          <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Company</a>
          -->
        </div>
        <div class="p-2">
          <% if current_user.present? %>
            <%= link_to dashboard_path, class: 'btn btn-secondary block w-full'  do %>
              <i class="icon far fa-sign-in "></i>Open App
            <% end %>
          <% else %>
            <%= link_to "Log in", new_user_session_url,  class: "btn btn-secondary block w-full mb-2" %>
            <%= link_to "Sign up for free", new_user_registration_url,  class: "btn btn-primary block w-full" %>
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_notification.html.erb
<%
  background_colors = {
    :error => 'bg-red-200',
    :info => 'bg-yellow-100',
    :success => 'bg-green-100',
  }

  text_colors = {
    :error => 'text-red-800',
    :info => 'text-yellow-800',
    :success => 'text-green-800',
  }

  icons = {
    :error => 'fa-exclamation-triangle',
    :info => 'fa-exclamation-circle',
    :success => 'fa-check-circle'
  }


  # define default values if arguments are not set
  type = local_assigns.fetch :type, :info
  type = type.to_sym
  if type == :alert
    type = :error
  else type == :notice
  type = :success
  end
%>

<div
  class="fixed bottom-1 left-1/2 transform -translate-x-1/2 z-20 rounded-md <%= background_colors[type] %> <%= background_colors[type] %> p-4"
  x-data="window.Notification()" x-show="show"
  x-init="init()"
  x-transition:enter="transition ease-out duration-100"
  x-transition:enter-start="opacity-0 transform scale-95"
  x-transition:enter-end="opacity-100 transform scale-100"
  x-transition:leave="transition ease-in duration-75"
  x-transition:leave-start="opacity-100 transform scale-100"
  x-transition:leave-end="opacity-0 transform scale-95"
>
  <div class="flex items-center">
    <div class="flex-shrink-0">
      <i class="fas <%= icons[type] %> <%= text_colors[type] %>"></i>
    </div>
    <div class="ml-3">
      <p class="text-sm leading-5 font-medium <%= text_colors[type] %>">
        <%= yield %>
      </p>
    </div>
    <div class="ml-auto pl-3">
      <button @click="show = false" class="inline-flex rounded-md p-2 <%= text_colors[type] %> hover:<%= background_colors[type] %> focus:outline-none focus:<%= background_colors[type] %> transition ease-in-out duration-150" aria-label="Dismiss">
        <i class="far fa-times"></i>
      </button>
    </div>
  </div>
</div>

app/views/shared/_page_heading.html.erb
<div class="flex flex-row border-b border-gray-200 pb-4 mb-4">
  <div class="flex-grow">
    <h1 class="mb-2"><%= title %></h1>
    <% if description %>
      <p class="text-gray-500 text-sm"><%= description %></p>
    <% end %>
  </div>
  <div class="flex ml-4 items-center justify-center">
    <%= yield %>
  </div>
</div>

app/views/shared/_radiogroup.html.erb
<%
  # f : the form
  # method: the name of the field
  # options: list of options
  #   value : the value of the option
  #   label : the label of the option
  #   description[optional] : the description of the option
%>
<fieldset x-init="this.value = this.$el.querySelector('input[type=radio]:checked').value" x-data="">
  <div class="bg-white rounded-md -space-y-px" >
    <% options.each_with_index do |option,index| %>
      <%
        first = index == 0
        last = index == options.length-1
        id = "#{f.object_name}_#{method}_#{option[:value].parameterize.underscore}"
        wrapper_class = ""
        if first
          wrapper_class = "#{wrapper_class} rounded-tl-md rounded-tr-md"
        end
        if last
          wrapper_class = "#{wrapper_class} rounded-bl-md rounded-br-md"
        end
      %>
      <div class="relative border p-4 flex <%= wrapper_class %>"  :class="{ 'bg-indigo-100 border-indigo-200 z-10' : value == '<%= option[:value] %>', 'border-gray-200' : value != '<%= option[:value] %>' }">
        <div class="flex items-center h-5">
          <%= f.radio_button method, option[:value], {class: "focus:ring-blue-700 h-4 w-4 text-blue-800 cursor-pointer border-gray-300", "x-model": "value"} %>
        </div>
        <label for="<%= id %>" class="ml-3 flex flex-col cursor-pointer w-full">
          <span class="block text-sm font-medium" :class="{ 'text-blue-900' : value == '<%= option[:value]  %>', 'text-gray-800' : value !== '<%= option[:value] %>' }">
            <%= option[:label] %>
          </span>
          <% unless option[:description].nil? %>
            <span class="block font-normal text-sm" :class="{ 'text-blue-800' : value == '<%= option[:value]  %>', 'text-gray-600' : value !== '<%= option[:value] %>' }">
              <%= option[:description] %>
            </span>
          <% end %>
        </label>
      </div>
    <% end %>
  </div>
</fieldset>