config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get 'consent' => 'welcome#consent'

  get 'dashboard' => "dashboard#index"

  get 'experimentation' => "experimentation#index"

  # onboarding
  scope :onboarding, as: :onboarding do
    get '' => 'onboarding#index'
    get 'habits' => 'onboarding#habits'
    post 'habits' => 'onboarding#set_habits'
    get 'reflections' => 'onboarding#reflection_settings'
    post 'reflections' => 'onboarding#set_reflection_settings'
    get 'samplings' => 'onboarding#sampling_settings'
    post 'samplings' => 'onboarding#set_sampling_settings'
    get 'client' => 'onboarding#client'
  end

  # Devise (login/logout) for HTML requests
  devise_for :users, controllers: { registrations: 'registrations' }, defaults: { format: :html }, path: '', sign_out_via: %i[get post delete], path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  devise_scope :user do
    get :settings, to: 'registrations#settings'
    put :settings, to: 'registrations#update_settings'
  end

  # resources will automatically create all CRUD paths
  # the only attribute can be used to limit it to certain actions
  resources :goals

  resources :habits do
    collection do
      get 'select'
      post 'clone'
    end
    member do
      post 'enable'
      post 'disable'
    end
  end

  resources :reflections
  resources :experience_sample_configs

  # API part
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'post/index'
      devise_scope :user do
        post :auth, to: 'sessions#create'
        delete :auth, to: 'sessions#destroy'
      end
      resources :users, only: %w[show] do
        resources :occurrences, only: [:index, :update]
        resources :samplings, only: [:index, :update]
      end
    end
    namespace :v2 do
      # Things yet to come
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  acts_as_paranoid # soft delete

  has_many :derivatives, class_name: 'Goal', foreign_key: 'template_id'
  has_many :experience_sample_configs, dependent: :destroy
  has_many :habits, dependent: :destroy # will also soft delete the habits if goal is soft deleted

  belongs_to :template, class_name: 'Goal', optional: true
  belongs_to :user


  validates :title, presence: true
  validates :is_template, inclusion: [false], if: :template_id? # cannot be template if associated with template
  validates :template_id, absence: true, if: :is_template? # must not have association to template if is_template

  enum color: { gray: 0, red: 1, yellow: 2, green: 3, blue: 4, indigo: 5, purple: 6, pink: 7 }

  def clone(user)
    unless self.is_template?
      raise "Only templates can be duplicated."
    end

    new_goal = self.dup
    new_goal.is_template = false
    new_goal.template_id = self.id
    new_goal.user = user
    new_goal.save!

    new_goal
  end

end

app/models/habit.rb
class Habit < ApplicationRecord
  acts_as_paranoid # soft delete

  belongs_to :goal, with_deleted: true
  belongs_to :user
  has_many :occurrences
  belongs_to :template, class_name: 'Habit', optional: true
  has_many :habit_reflections
  has_many :reflections, through: :habit_reflections

  validates :title, presence: true
  validates :is_template, inclusion: [false], if: :template_id? # cannot be template if associated with template
  validates :template_id, absence: true, if: :is_template? # must not have association to template if is_template

  # all the historical configs for this habit
  has_many :configs, :class_name => 'Habit::Config', inverse_of: 'habit'

  # the current config for this habit
  belongs_to :current_config, class_name: 'Habit::Config', foreign_key: 'current_config_id', optional: true

  # Delegate to habit_config so attributes are available on habit as well
  delegate :duration, :schedule, :is_skippable, :is_enabled, :recurrence_on, :recurrence_at, to: :current_config, allow_nil: true

  before_destroy :before_destroy
  after_recover :reschedule_occurrences # after soft delete recovery

  def before_destroy
    destroy_occurrences
    destroy_configs
    destroy_habit_reflections
  end

  def destroy_habit_reflections
    if deleted?
      habit_reflections.delete_all
    end
  end

  def destroy_occurrences
    if deleted?
      occurrences.delete_all
    else
      occurrences.where("scheduled_at >= ?", DateTime.now).delete_all
    end
  end

  def reschedule_occurrences
    current_config.schedule_occurrences(DateTime.now)
  end

  # we're manually doing the destroy since there is a circular dependency between habit <-> current_config
  # that results in a ForeignKey violation otherwise
  def destroy_configs
    if deleted?
      Habit.transaction do
        config = current_config
        update({current_config: nil})
        config.destroy
        Config.where(habit_id: id).delete_all
      end
    end
  end

  # Creates a clone of the habit (including its habit config)
  def clone(user)
    unless self.is_template?
      raise "Only templates can be duplicated."
    end

    new_habit = self.dup
    new_habit.is_template = false
    new_habit.user = user
    new_habit.template_id = self.id
    new_config = self.current_config.dup
    new_habit.current_config = new_config
    new_config.habit = new_habit
    new_habit.save!

    new_habit
  end

  def enable
    self.set_is_enabled(true)
  end

  def disable
    self.set_is_enabled(false)
  end

  private
    def set_is_enabled(is_enabled = true)
      ActiveRecord::Base.transaction do
        new_config = current_config.dup
        new_config.is_enabled=is_enabled
        new_config.save!
        self.current_config = new_config
        self.save!
        raise ActiveRecord::Rollback unless errors.empty?
      end
      errors.empty?
    end

end

app/models/habit/config.rb
require 'time'

class Habit::Config < ApplicationRecord
  include ActiveRecord::Immutable

  include Schedulable
  include_schedule :schedule

  self.table_name = "habit_configs"

  belongs_to :habit
  has_many :occurrences, through: :habit

  validates :duration, numericality: { only_integer: true}
  after_save :schedule_occurrences # TODO: later this action must be performed when a habit is *duplicated* and on a daily schedule


  def schedule_occurrences(starting_from = self.updated_at, retention_period = 7.days)
    # 1. remove all occurrences newer than current updated_at
    occurrences.where("scheduled_at >= ?", starting_from).delete_all

    # 2. create new occurrences newer than current updated_at if habit is enabled
    if is_enabled
      dates = self.get_schedule(starting: starting_from, ending: (starting_from + retention_period).at_end_of_day)
      dates.each do |date|
        Occurrence.create(habit_id: self.habit_id, scheduled_at: date)
      end
    end
  end

end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ show edit update destroy enable disable ]
  before_action :authenticate_user!

  layout 'boxed' # sets the layout for all views with this controller

  # GET /habits or /habits.json
  def index
    show = params[:show].to_s
    case show
    when "templates"
      @habits = policy_scope(Habit).where(is_template: true)
    when "own"
      @habits = current_user.habits
    when "trash"
      @habits = policy_scope(Habit).only_deleted
    else
      @habits = policy_scope(Habit)
    end

  end

  # view for selecting a new habit (based on a template)
  def select
    @goals = Habit.where(is_template: true).where(goal: { is_template: true}).includes([:goal, :current_config]).group_by{ |habit| habit.goal_id }
  end

  # action for cloning the templates
  def clone
    @habit_ids = params[:habit_ids]

    # TODO: what to do with duplicate habits? e.g. the user already has a clone of that habit?

    # 1. get list of selected habits
    @habits = Habit.where(id:@habit_ids)

    @habit_path = habits_path
    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : @habit_path


    if @habits.present?
      Habit.transaction do
        # 2. duplicate habits and habit config
        # the habits are now cloned but still have the old goals assigned to them
        new_habits = @habits.map{ |habit| habit.clone(current_user)}
        # 3. loop over all the new habits
        new_habits.each do |habit|
          # check if user already has a goal that was derived from that template
          existing_goal = current_user.goals.where(template_id: habit.goal_id).first
          if existing_goal.present?
            # change goal to existing user's goal with same template_id
            habit.update(goal: existing_goal)
          else
            new_goal = habit.goal.clone(current_user)
            habit.update(goal: new_goal)
          end
        end
      end
      redirect_to return_to, notice: "Successfully created #{@habits.count} habits."
    else
      redirect_to select_habits_path, alert: "Please select at least one habit."
    end
  end

  # GET /habits/1 or /habits/1.json
  def show
    authorize @habit
    @occurrences = @habit.occurrences.order(scheduled_at: :asc)
    @configs = @habit.configs.order(created_at: :desc)
  end

  # GET /habits/new
  def new
    @habit = HabitForm.new(user: current_user, is_enabled: true)
  end

  # GET /habits/1/edit
  def edit
    authorize @habit
  end

  # POST /habits or /habits.json
  def create

    if habit_params[:user_id].nil? and habit_params[:user].nil? and !policy(@habit).set_user?
      habit_params[:user] = current_user
    end

    @habit = HabitForm.new(habit_params)

    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : @habit

    if @habit.save
      redirect_to return_to, notice: "Habit was successfully created."
    else
      render :new, status: :unprocessable_entity
    end

  end


  def disable
    authorize @habit

    unless @habit.is_enabled
      redirect_to @habit_path, alert: "Habit is already disabled."
    end

    @habit_path = habit_path(@habit.id)
    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : @habit_path

    if @habit.disable
      redirect_to return_to, notice: "Habit was successfully disabled."
    else
      redirect_to @habit_path, alert: "Habit could not be disabled."
    end
  end

  def enable
    authorize @habit

    if @habit.is_enabled
      redirect_to @habit_path, alert: "Habit is already enabled."
    end

    @habit_path = habit_path(@habit.id)
    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : @habit_path

    if @habit.enable
      redirect_to return_to, notice: "Habit was successfully enabled."
    else
      redirect_to @habit_path, alert: "Habit could not be enabled."
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    authorize @habit
    @habit_form = HabitForm.new(habit_params.merge("id" => params[:id]))
    @habit_path = habit_path(@habit_form.id)
    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : @habit_path

    if @habit_form.update(habit_params)
      redirect_to return_to, notice: "Habit was successfully updated."
    else
      render @habit_path, status: :unprocessable_entity
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    authorize @habit
    message = @habit.deleted_at.present? ? "Habit was successfully destroyed." : "Habit was put in trash."

    return_to = params[:redirect_to].to_s.present? ? params[:redirect_to].to_s : habits_url

    @habit.destroy
    redirect_to return_to, notice: message
  end

  def set_recurrence_from_param
    type = habit_params[:recurrence_type] # :week, :day
    on = habit_params[:recurrence_on]
    at = habit_params[:recurrence_at]
    @habit.add_recurrence(type: type, on: on, at: at)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:title, :description, :goal_id, :user_id, :recurrence_type, :duration, :is_template, :is_skippable, :is_enabled, :type,:recurrence_at, :recurrence_on => [])
    end
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_form.html.erb
<%= form_for(habit) do |form| %>
  <% if defined?(redirect_to) && !redirect_to.blank? && !redirect_to.nil? %>
    <%= hidden_field_tag 'redirect_to', redirect_to %>
  <% end %>

  <% if habit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>

      <ul>
        <% habit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="">
    <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title %>
        </div>
      </div>
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description, rows: 2 %>
        </div>
      </div>
      <div class="sm:col-span-3">
        <div class="field">
          <%= form.label :recurrence_on, "On" %>
          <div class="grid grid-flow-col grid-cols-3 grid-rows-3 gap-2">
            <% [ {label: "Mon", value: "monday"}, {label: "Tue", value: "tuesday"}, {label: "Wed", value: "wednesday"}, {label: "Thu", value: "thursday"}, {label: "Fri", value: "friday"}, {label: "Sat", value: "saturday"}, {label: "Sun", value: "sunday"}].each_with_index do |day,i| %>
              <div class="relative flex items-start">
                <div class="flex items-center h-5">
                  <%= form.check_box :recurrence_on, { multiple: true, id: "day_#{i}" }, day[:value], false %>
                </div>
                <div class="ml-3 text-sm">
                  <%= form.label day[:label], for: "day_#{i}" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="sm:col-span-3">
        <div class="field">
          <%= form.label :recurrence_at, "At" %>
          <%= form.text_field :recurrence_at,  {class: 'js-choice', multiple: false} %>
          <p class="mt-2 text-sm text-gray-500" id="email-description">Format: HH:MM. Separate multiple values with a comma.</p>
        </div>
      </div>
      <div class="sm:col-span-3">
        <div class="field">
          <%= form.label :duration, "Duration" %>
          <div class="relative">
            <%= form.number_field :duration %>
            <div class="absolute inset-y-0 right-4 pr-5 flex items-center pointer-events-none">
              <span class="text-gray-500 sm:text-sm" id="price-currency">
                min
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="sm:col-span-6">
        <div class="field">
          <%= form.label :goal_id %>
          <%= form.select :goal_id, policy_scope(Goal).collect { |g| [ g.title, g.id]} %>
        </div>
      </div>
      <div class="sm:col-span-2">
        <div class="field">
          <%= form.label :is_skippable %>
          <%= form.check_box :is_skippable %>
        </div>
      </div>
      <div class="sm:col-span-2">
        <div class="field">
          <%= form.label :is_enabled %>
          <%= form.check_box :is_enabled %>
        </div>
      </div>
      <% if policy(habit).set_template? %>
        <div class="sm:col-span-2">
          <div class="field">
            <%= form.label :is_template %>
            <%= form.check_box :is_template %>
          </div>
        </div>
      <% else %>
        <%= form.hidden_field :is_template %>
      <% end %>
      <% if policy(habit).set_user? %>
        <div class="sm:col-span-6">
          <div class="field">
            <%= form.label :user_id %>
            <%= form.select :user_id, User.all.collect { |u| [ u.username, u.id]} %>
          </div>
        </div>
      <% else %>
        <%= form.hidden_field :user_id %>
      <% end %>
    </div>
  </div>

  <div class="flex my-4">
    <%= form.submit class: 'btn btn-primary' %>
    <% if habit.persisted? %>
      <% if defined?(redirect_to) && !redirect_to.blank? && !redirect_to.nil? %>
        <%= link_to habit_url(habit, redirect_to: redirect_to), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary ml-auto'  do %>
          <i class="icon far fa-trash-alt "></i>Delete Habit
        <% end %>
      <% else %>
        <%= link_to habit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-secondary ml-auto'  do %>
          <i class="icon far fa-trash-alt "></i>Delete Habit
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/habits/_habit_list.html.erb
<li>
  <a href="<%= habit_url(habit) %>" class="flex flex-row hover:bg-gray-50 <%= habit.is_enabled ? "" : "opacity-50" %>">
    <div class="flex-none w-1 mr-1 <%= color_bg_class(habit.goal.color) %>"></div>
    <div class="flex flex-grow flex-col px-4 py-4">
      <div class="flex items-center justify-between">
        <div class="flex flex-col">
          <div class="flex flex-row">
            <p class="text-sm font-medium text-gray-900 truncate">
              <%= habit.title %>
            </p>
            <% unless habit.is_enabled %>
              <div class="ml-2 px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                Disabled
              </div>
            <% end %>
          </div>

          <% if habit.description.present? %>
            <p class="text-sm text-gray-500 truncate">
              <%= habit.description %>
            </p>
          <% end %>
        </div>
        <div class="ml-2 flex-shrink-0 flex">
          <% if habit.is_skippable %>
            <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
              Skippable
            </p>
          <% end %>
          <% if habit.is_template %>
            <p class="ml-2 px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
              Template
            </p>
          <% end %>
        </div>
      </div>
      <div class="mt-2 sm:flex sm:justify-between">
        <div class="sm:flex">
          <p class="flex items-center text-sm text-gray-500">
            <i class="far fa-bullseye-arrow mr-2"></i>
            <%= habit.goal.title %>
          </p>
          <p class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0 sm:ml-6">
            <i class="far fa-user mr-2"></i>
            <%= habit.user.username %>
          </p>
        </div>
        <div class="sm:flex">
          <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
            <i class="far fa-calendar-alt mr-2"></i>
            <p>
              <%= habit.recurrence_on.map{|day| day.slice(0,2)}.join(', ') %> at <%= habit.recurrence_at %>
            </p>
          </div>
          <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0 ml-6">
            <i class="far fa-clock mr-2"></i>
            <p>
              <%= habit.duration %> mins
            </p>
          </div>
        </div>
      </div>
    </div>
  </a>
</li>

app/views/habits/_habit_select_list.html.erb
<label class="my-2 relative block rounded-lg border border-gray-300 bg-white shadow-sm px-6 py-4 cursor-pointer hover:border-gray-400 sm:flex sm:justify-between focus-within:ring-1 focus-within:ring-offset-2 focus-within:ring-gray-400" x-data="{ selected: false }">
  <input type="checkbox" name="habit_ids[]" x-model="selected" value="<%= habit.id %>" class="sr-only" aria-labelledby="server-size-0-label" aria-describedby="server-size-0-description-0 server-size-0-description-1">
  <div class="flex items-center">
    <div class="text-sm">
      <p  class="font-medium text-gray-900">
        <%= habit.title %>
      </p>
      <% if habit.description.present? %>
        <div class="text-gray-500 flex">
          <%= habit.description %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="server-size-0-description-1" class="mt-2 flex text-sm sm:mt-0 sm:block sm:ml-4 sm:text-right">
    <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
      <i class="far fa-calendar-alt mr-2"></i>
      <p>
        <%= habit.recurrence_on.map{|day| day.capitalize.slice(0,2)}.join(', ') %> at <%= habit.recurrence_at %>
      </p>
    </div>
    <div class="mt-2 flex items-center justify-end text-sm text-gray-500 sm:mt-0 ml-6">
      <i class="far fa-clock mr-2"></i>
      <p>
        <%= habit.duration %> mins
      </p>
    </div>
  </div>
  <div :class="{ 'border-transparent': !selected, 'border-gray-900': selected }" class="absolute -inset-px rounded-lg border-2 pointer-events-none" aria-hidden="true"></div>
</label>

app/views/habits/_toggle.html.erb
<%

  enabled_btn_css = "flex focus-visible:ring-2 focus-visible:ring-gray-900 focus-visible:ring-offset-2 rounded-md focus:outline-none focus-visible:ring-offset-gray-100";
  enabled_text_css = ""

%>

<div class="group p-0.5 rounded-lg flex bg-gray-100 hover:bg-gray-200 mr-4">

  <% if habit.is_enabled %>
    <div class="flex focus-visible:ring-2 focus-visible:ring-gray-900 focus-visible:ring-offset-2 rounded-md focus:outline-none focus-visible:ring-offset-gray-100">
      <span class="p-2 rounded-md flex items-center text-sm font-medium bg-white shadow-sm ring-1 ring-black ring-opacity-5" >
        <i class="far fa-eye mr-1"></i>
        <span class="sr-only lg:not-sr-only text-gray-900">Enabled</span>
      </span>
    </div>
    <%= link_to disable_habit_url(habit), method: :post, class: "ml-0.5 p-1.5 lg:pl-2.5 lg:pr-3.5 rounded-md flex items-center text-sm text-gray-600 font-medium focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2 focus:outline-none focus-visible:ring-offset-gray-100" do %>
      <i class="far fa-eye-slash mr-1"></i>
      <span class="sr-only lg:not-sr-only text-gray-600 hover:text-gray-900">Disable</span>
    <% end %>
  <% else %>
    <%= link_to enable_habit_url(habit), method: :post, class: "ml-0.5 p-1.5 lg:pl-2.5 lg:pr-3.5 rounded-md flex items-center text-sm text-gray-600 font-medium focus-visible:ring-2 focus-visible:ring-teal-500 focus-visible:ring-offset-2 focus:outline-none focus-visible:ring-offset-gray-100" do %>
      <i class="far fa-eye mr-1"></i>
      <span class="sr-only lg:not-sr-only text-gray-600 hover:text-gray-900">Enable</span>
    <% end %>
    <div class="flex focus-visible:ring-2 focus-visible:ring-gray-900 focus-visible:ring-offset-2 rounded-md focus:outline-none focus-visible:ring-offset-gray-100">
      <span class="p-2 rounded-md flex items-center text-sm font-medium bg-white shadow-sm ring-1 ring-black ring-opacity-5" >
        <i class="far fa-eye-slash mr-1"></i>
        <span class="sr-only lg:not-sr-only text-gray-900">Disabled</span>
      </span>
    </div>
  <% end %>


</div>

app/views/habits/edit.html.erb
<h1>Editing Habit</h1>

<%= render 'form', habit: @habit %>

app/views/habits/index.html.erb
<%= render 'shared/page_heading', title: "Habits", description: "Habits are activities that you are trying to establish to achieve your goals." do %>
  <%= link_to select_habits_path, class: 'btn btn-secondary mr-2'  do %>
    <i class="icon far fa-magic "></i>Select Template
  <% end %>
  <%= link_to 'New Habit', new_habit_path, class: "btn btn-primary flex" %>
<% end %>
<% if policy(Habit).see_all? %>
  <div class="flex flex-row mb-4 items-center justify-end">
    <%= render 'shared/buttongroup', options: [{ title: "All", link: habits_path}, { title: "Own", link: habits_path(:show => :own)}, { title: "Templates", link: habits_path(:show => :templates)}, { title: "Trash", link: habits_path(:show => :trash)}] %>
  </div>
<% end %>

<%= render 'shared/boxed_list' do %>
  <% @habits.each_with_index do |habit,index| %>
    <%= render 'habit_list', habit: habit, index: index %>
  <% end %>
<% end %>

app/views/habits/new.html.erb
<h1>New Habit</h1>

<%= render 'form', habit: @habit %>

<%= link_to 'Back', habits_path %>

app/views/habits/select.html.erb
<%= render 'shared/page_heading', title: "Select Habits", description: "Select a number of habits that you want to establish for yourself. You can adjust the schedule and the duration for each habit afterwards." do %>

<% end %>
<div class="grid ">
  <% if @goals.present? %>
    <%= form_with(url: clone_habits_path, method: "post") do |form| %>

      <% @goals.each do |goal_id, habits| %>
        <div class="mb-8">
        <div class="mb-4">
          <h3 class="mb-1"><%= habits.first.goal.title %></h3>
          <p class="text-sm text-gray-500"><%= habits.first.goal.description %></p>
        </div>
        <% habits.each_with_index do |habit,index| %>
          <%= render 'habit_select_list', habit: habit %>
        <% end %>
        </div>
      <% end %>
      <%= form.submit 'Select Habits', class: 'btn btn-primary mt-2' %>
    <% end %>
  <% else %>
    <p class="text-gray-500">There are currently no habits available as a template.</p>
  <% end %>
</div>

app/views/habits/show.html.erb
<%= render 'shared/page_heading', title: @habit.title, description: @habit.description do %>
  <%= render 'toggle', habit: @habit %>
  <%= link_to edit_habit_path(@habit), class: 'btn btn-primary flex whitespace-nowrap' do %>
    <i class="fas fa-pencil-alt mr-2"></i>Edit
  <% end %>
<% end %>
<% unless @habit.is_enabled %>
  <div class="rounded-md bg-gray-100 border border-gray-200 my-4 p-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <i class="far fa-info-circle h-5 w-5 text-gray-400"></i>
      </div>
      <div class="ml-3 flex-1 md:flex md:justify-between">
        <div class="m-0 text-gray-700 text-sm">
          This habit is disabled. It will not show up on the dashboard and you will not receive any notifications.
        </div>
      </div>
    </div>
  </div>
<% end %>

<p>
  <strong>Goal:</strong>
  <%= @habit.goal.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @habit.user.username %>
</p>

<h3 class="mt-8">History:</h3>

<%= render 'shared/table/wrapper' do %>
  <thead class="bg-gray-50">
  <tr>
    <%= render 'shared/table/heading', title: "Schedule" %>
    <%= render 'shared/table/heading', title: "Duration" %>
    <%= render 'shared/table/heading', title: "Enabled" %>
    <%= render 'shared/table/heading', title: "Skippable" %>
    <%= render 'shared/table/heading', title: "Created" %>
  </tr>
  </thead>
  <tbody>
  <% @configs.each_with_index do |config,index| %>
    <%= render 'shared/table/row', odd: index.even? do %>
      <%= render 'shared/table/cell' do %>
        <%= config.recurrence_on.map{|day| day.slice(0,2)}.join(', ') %> at <%= config.recurrence_at %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= config.duration %> mins
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= config.is_enabled ? "yes" : "no" %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= config.is_skippable ? "yes" : "no" %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= time_ago_in_words(config.created_at) %> ago
      <% end %>
    <% end %>
  <% end %>
  </tbody>
<% end %>


<h3 class="mt-8">Occurrences:</h3>
<%= render 'shared/table/wrapper' do %>
  <thead class="bg-gray-50">
  <tr>
    <%= render 'shared/table/heading', title: "ID" %>
    <%= render 'shared/table/heading', title: "Scheduled" %>
    <%= render 'shared/table/heading', title: "Started" %>
    <%= render 'shared/table/heading', title: "Ended" %>
    <%= render 'shared/table/heading', title: "Skipped" %>
  </tr>
  </thead>
  <tbody>
  <% @occurrences.each_with_index do |occurrence,index| %>
    <%= render 'shared/table/row', odd: index.even? do %>
      <%= render 'shared/table/cell' do %>
        <%= occurrence.id %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= occurrence.scheduled_at.strftime("%F %H:%M") %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= occurrence.started_at&.strftime("%F %H:%M") %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= occurrence.ended_at&.strftime("%F %H:%M") %>
      <% end %>
      <%= render 'shared/table/cell' do %>
        <%= occurrence.skipped_at&.strftime("%F %H:%M") %>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
<% end %>